GrievanceSystem_Mvc/Controllers/SubcategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GrievanceSystem_Mvc.ServiceLayer;
using GrievanceSystem_Mvc.ViewModels;

namespace GrievanceSystem_Mvc.Controllers
{
    [Authorize(Roles = "Admin ,Pricipal")]
    public class SubcategoryController : Controller
    {
        readonly ISubcategoryService sc;
        readonly ICategoryService cs;
        public SubcategoryController(ISubcategoryService sc, ICategoryService cs)
        {
            this.sc = sc;
            this.cs = cs;

        }
        // GET: Subategory
        public ActionResult Index()
        {
            CategoryViewModel c = new CategoryViewModel()
            {
                CategoryID = 0,
                CategoryName = "All"
            };
            List<CategoryViewModel> categories = cs.GetCategory().ToList();
            categories.Insert(0, c);
            ViewBag.categories = categories;
            return View();
        }

        // GET: Subategory/GetSubcategories/5
        public ActionResult GetSubcategories()
        {
            List<SubcategoryViewModel> Subcategories = sc.GetSubcategory();
            return Json(new { data = Subcategories }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetSubcategoriesByCategoryId(int id)
        {
            List<SubcategoryViewModel> Subcategories;
            if (id == 0)
            {
                Subcategories = sc.GetSubcategory();

            }
            else
            {
                Subcategories = sc.GetSubcategoryByCategoryId(id);

            }
            return Json(new { data = Subcategories }, JsonRequestBehavior.AllowGet);

        }



        // GET: Subcategory/Create
        public ActionResult Create()
        {
            //form here we need to pass list of category

            List<CategoryViewModel> categories = cs.GetCategory().ToList();
            ViewBag.categories = categories;
            return View();
        }

        // POST: Category/Create
        [HttpPost]
        public ActionResult Create(NewSubcategoryViewModel subcategory, FormCollection collection)
        {
            int rowAffected = sc.InsertSubcategory(subcategory);
            //changes
            if (rowAffected == 0)
            {
                return new JsonResult { Data = new { result = false, message = "data was not saved successfully!" } };

            }
            else
            {
                return new JsonResult { Data = new { result = true, message = "data saved successfully!" } };

            }
        }

        public ActionResult Edit(int id)
        {
            List<CategoryViewModel> categories = cs.GetCategory().ToList();
            ViewBag.categories = categories;

            SubcategoryViewModel subcategory = sc.GetSubategoryById(id);
            EditSubcategoryViewModel editsubcategory = new EditSubcategoryViewModel()
            {
                SubcategoryID = subcategory.SubcategoryID,
                SubcategoryName = subcategory.SubcategoryName,
                Category_ID = subcategory.Category_ID
            };
            return View(editsubcategory);
        }

        // POST: Category/Edit/5
        [HttpPost]
        public ActionResult Edit(EditSubcategoryViewModel editSubcategory, FormCollection collection)
        {
            if (ModelState.IsValid)
            {
                int rowAffected = sc.UpdateSubcategory(editSubcategory);
                if (rowAffected == 0)
                {
                    return new JsonResult { Data = new { result = false, message = "data was not Updated successfully!" } };
                }
                else
                {
                    return new JsonResult { Data = new { result = true, message = "data Updated successfully!" } };
                }
            }
            else
            {
                ModelState.AddModelError("Error", "Please Enter valid data");
                return View(editSubcategory);

            }
        }

        // GET: Category/Delete/5
        public ActionResult Delete(int id)
        {
            SubcategoryViewModel subcategory = sc.GetSubategoryById(id);
            return View(subcategory);
        }

        // POST: Category/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            int rowAffected = sc.DeleteSubcategory(id);
            if (rowAffected == 0)
            {
                return new JsonResult { Data = new { result = false, message = "data was not Deleted successfully!" } };
            }
            else
            {
                return new JsonResult { Data = new { result = true, message = "data Deleted successfully!" } };
            }
        }
    }
}

GrievanceSystem_Mvc/Views/Subcategory/Create.cshtml
@model GrievanceSystem_Mvc.ViewModels.NewSubcategoryViewModel
@{
	Layout = null;
}


<div class="row mt-5 pt-5 justify-content-center">
	<div class="col-md-8">
		@using (Html.BeginForm("Create", "Subcategory", FormMethod.Post, new { id = "RegistrationForm" }))
		{
			@Html.AntiForgeryToken()
			<div class="form-horizontal">

				@Html.ValidationSummary(true, "", new { @class = "text-danger" })

				<div class="form-group">
					@Html.Label("Category", htmlAttributes: new { @class = "control-label col-md" })
					<div class="col-md">
						@Html.DropDownListFor(m => m.Category_ID, new SelectList(ViewBag.categories as System.Collections.IEnumerable, "CategoryID", "CategoryName"), "--select category--", new { id = "Category", @class = "form-control input-width" })
						@Html.ValidationMessageFor(model => model.Category_ID, "", new { @class = "text-danger" })
					</div>
				</div>

				<div class="form-group">
					@Html.LabelFor(model => model.SubcategoryName, htmlAttributes: new { @class = "control-label col-md" })
					<div class="col-md">
						@Html.TextBoxFor(model => model.SubcategoryName, new { @class = "form-control" })
						@Html.ValidationMessageFor(model => model.SubcategoryName, "", new { @class = "text-danger" })
					</div>
				</div>

				<div class="form-group">
					<p class="col-md mb-3 text-center mt-2 ">
						<input type="submit" value="Add" class="btn btn-info mx-2 shadow-none ">
						<input type="reset" value="Reset" class="btn btn-secondary mx-2 shadow-none ">
					</p>
				</div>
			</div>
		}
	</div>
</div>

GrievanceSystem_Mvc/Views/Subcategory/Delete.cshtml
@model GrievanceSystem_Mvc.ViewModels.SubcategoryViewModel

@{
	Layout = null;
}

<div class="row mt-5 pt-5 justify-content-center">
	<div class="col-md-8">


		@using (Html.BeginForm("Delete", "Subcategory", FormMethod.Post, new { id = "RegistrationForm" }))
		{
			@Html.AntiForgeryToken()
			@Html.HiddenFor(x => x.SubcategoryID)

			<div class="form-horizontal">
			
				<div class="form-group">
					@Html.LabelFor(model => model.SubcategoryName, htmlAttributes: new { @class = "control-label col-md" })
					<div class="col-md">
						@Html.TextBoxFor(model => model.SubcategoryName, new { @class = "form-control" })
					</div>
				</div>
			
				<div class="form-group">
					<p class="col-md mb-3 text-center mt-2 ">
						<input type="submit" value="Delete" class="btn btn-danger mx-2 shadow-none ">
					</p>
				</div>
			</div>

		}

	</div>
</div>

GrievanceSystem_Mvc/Views/Subcategory/Edit.cshtml
@model GrievanceSystem_Mvc.ViewModels.EditSubcategoryViewModel
@{

	Layout = null;
}

<div class="row mt-5 pt-5 justify-content-center">
	<div class="col-md-8">
		@using (Html.BeginForm("Edit", "Subcategory", FormMethod.Post, new { id = "RegistrationForm" }))
		{
			@Html.AntiForgeryToken()
			<div class="form-horizontal">

				@Html.ValidationSummary(true, "", new { @class = "text-danger" })
				@Html.HiddenFor(x => x.SubcategoryID)

				<div class="form-group">
					@Html.Label("Category", htmlAttributes: new { @class = "control-label col-md" })
					<div class="col-md">
						@Html.DropDownListFor(m => m.Category_ID, new SelectList(ViewBag.categories as System.Collections.IEnumerable, "CategoryID", "CategoryName"), "--select category--", new { id = "Category", @class = "form-control input-width" })
						@Html.ValidationMessageFor(model => model.Category_ID, "", new { @class = "text-danger" })
					</div>
				</div>

				<div class="form-group">
					@Html.LabelFor(model => model.SubcategoryName, htmlAttributes: new { @class = "control-label col-md" })
					<div class="col-md">
						@Html.TextBoxFor(model => model.SubcategoryName, new { @class = "form-control" })
						@Html.ValidationMessageFor(model => model.SubcategoryName, "", new { @class = "text-danger" })
					</div>
				</div>

				<div class="form-group">
					<p class="col-md mb-3 text-center mt-2">
						<input type="submit" value="Save Changes" class="btn btn-info shadow-none">
					</p>
				</div>
			</div>
		}
	</div>
</div>

GrievanceSystem_Mvc/Views/Subcategory/Index.cshtml
@{
	ViewBag.Title = "Index";
	Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="container card my-4 Subcategorycontainer">

	<div class="row p-3">
		<div class="col-md-12">

			<span class="h5 pt-1"><strong>Subcategories</strong></span>

			<a href="/Subcategory/Create" class="btn btn-outline-primary float-right shadow-none Subcategorypopup" id="addSubcategory" title="Add Subcategory">
				<span class="px-3 font-weight-bold">
					<i class="fa fa-plus"> </i> Add Subcategory
				</span>
			</a>
		</div>
	</div>

	<hr class="m-0" />
	<div class="row  p-4">
		<div class="col-md-12">
			<div class="form-group">
				@Html.Label("Category", htmlAttributes: new { @class = "control-label col-md" })
				<div class="col-md-5 p-0">
					@Html.DropDownList("Category", new SelectList(ViewBag.categories as System.Collections.IEnumerable, "CategoryID", "CategoryName"), new { id = "ddc_Category", @class = "form-control input-width" })
				</div>
			</div>
			<table class="table table-responsive table-sm table-striped table-bordered " id="SubcategoryTable" style="width:100%;">
				<thead>
					<tr>
						<th style="width:100%">
							Subcategory Name
						</th>
						<th class="" style=" max-width: 175px; width: 175px; min-width: 175px;">Actions</th>
					</tr>
				</thead>
			</table>
		</div>
	</div>

</div>