GrievanceSystem_Mvc/Controllers/GrievanceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GrievanceSystem_Mvc.ServiceLayer;
using GrievanceSystem_Mvc.ViewModels;
using System.IO;
using GrievanceSystem_Mvc.Models;

namespace GrievanceSystem_Mvc.Controllers
{
    [Authorize]
    public class GrievanceController : Controller
    {

        readonly IGrievanceService gs;
        readonly ICategoryService cs;
        readonly ISubcategoryService ss;
        readonly IReplyService rs;
        readonly IUserService us;

        public GrievanceController(IGrievanceService gs, ICategoryService cs, ISubcategoryService ss, IReplyService rs, IUserService us)
        {
            this.gs = gs;
            this.cs = cs;
            this.ss = ss;
            this.rs = rs;
            this.us = us;
        }

        //based on user id we need to provide  grieviences and for admin/commitee member we need to provide complete list 
        //we dont need to get userid from view we cant get it from session variable also TODO:
        [HttpGet]
        [Authorize(Roles = "Student")]
        public ActionResult Index()
        {

            int userId = Convert.ToInt32(Session["CurrentUserID"]);

            List<GrievanceViewModel> grievanceViewModels = gs.GetGrievanceByUserId(userId);
            if (grievanceViewModels == null)
            {
                ViewData["Error"] = "Record Not Found Please try again";
                return View("Error");
            }

            return View(grievanceViewModels);

        }

        [HttpGet]
        [Authorize(Roles = "Admin ,Pricipal,Committee Member")]
        public ActionResult AllGrievances()
        {
            //TODO: Work on views buttons and all
            return View();

        }


        [Authorize(Roles = "Admin ,Pricipal,Committee Member")]
        public ActionResult GetAllGrievances()
        {
            //TODO: Work on views buttons and all

            List<GrievanceViewModel> grievances = gs.GetGrievance();

            return Json(new { data = grievances }, JsonRequestBehavior.AllowGet);

        }

        [HttpGet]
        [Authorize(Roles = "Admin ,Pricipal,Committee Member")]
        public ActionResult PendingGrievances()
        {
            //TODO: Work on views buttons and all
            return View();

        }


        [Authorize(Roles = "Admin ,Pricipal,Committee Member")]
        public ActionResult GetPendingGrievances()
        {
            //TODO: Work on views buttons and all

            List<GrievanceViewModel> grievances = gs.GetPendingGrievances();

            return Json(new { data = grievances }, JsonRequestBehavior.AllowGet);

        }

        [HttpGet]
        [Authorize(Roles = "Admin ,Pricipal,Committee Member")]
        public ActionResult ResolvedGrievances()
        {
            //TODO: Work on views buttons and all
            return View();

        }


        [Authorize(Roles = "Admin ,Pricipal,Committee Member")]
        public ActionResult GetResolvedGrievances()
        {
            //TODO: Work on views buttons and all

            List<GrievanceViewModel> grievances = gs.GetResolvedGrievances();

            return Json(new { data = grievances }, JsonRequestBehavior.AllowGet);

        }

        public ActionResult Details(int id)
        {
            GrievanceViewModel gvm = gs.GetGrievanceByGrievanceId(id);
            if (gvm.reply == null)
            {
                ReplyViewModel reply = new ReplyViewModel();
                gvm.reply = reply;

            }

            return View(gvm);


        }


        [HttpGet]
        [Authorize(Roles = "Student")]
        public ActionResult Create()
        {

            List<CategoryViewModel> categories = cs.GetCategory().ToList();
            ViewBag.categories = categories;
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Student")]
        public ActionResult Create(NewGrievanceViewModel newGrievance, HttpPostedFileBase file)
        {
            int userId = Convert.ToInt32(Session["CurrentUserID"]);
            string userName = Session["CurrentUserName"].ToString();
            string emailAddress = Session["CurrentUserEmail"].ToString();

            newGrievance.user_id = userId;
            newGrievance.status_id = 1;

            string uniqueFileName = null;

            if (file != null)
            {
                //set the path to receive file 
                string uploadPath = Server.MapPath(Helper.SetFilePath());


                string fileName = Path.GetFileName(file.FileName);
                uniqueFileName = Guid.NewGuid().ToString() + "_" + fileName;

                string filePath = Path.Combine(uploadPath, uniqueFileName);

                file.SaveAs(filePath);
            }

            newGrievance.file = uniqueFileName;

            int rowAffected = gs.InsertGrievanceDetails(newGrievance);
            if (rowAffected == 0)
            {
                ViewData["Error"] = "Data is not inserted for some reason kindly try after some time ";
                return View("Error");
            }
            else
            {

                //after data insertion Happen you can send email 

                string emailBody = Helper.GenerateEmailBody(userName, emailAddress, newGrievance);

                Helper.SendMail(emailAddress, emailBody);

                return RedirectToAction("Index");
            }
        }



        public ActionResult Edit(int id)
        {
            //TODO : on view we dont get exact category and subcategory we need to get category id and subcat id so or something else idk 

            List<CategoryViewModel> categories = GetCategories().ToList();
            ViewBag.categories = categories;

            List<SubcategoryViewModel> subcategories = GetSubcategories().ToList();
            ViewBag.subcategories = subcategories;

            //here we need to get subcat aslo and we need to remove onchange event for dropbox for the instance :done
            GrievanceViewModel grievanceViewModel = gs.GetGrievanceByGrievanceId(id);
            if (grievanceViewModel == null)
            {
                ViewData["Error"] = "Record Not Found Please try again";
                return View("Error");
            }
            return View(grievanceViewModel);

        }


        [HttpPost]
        public ActionResult Edit(EditGrievanceViewModel GrievanceViewModel, FormCollection form)
        {

            GrievanceViewModel.Category_ID = Convert.ToInt32(Request.Form["category.CategoryID"]);
            GrievanceViewModel.Subcategory_ID = Convert.ToInt32(Request.Form["subcategory.SubcategoryID"]);
            int rowAffected = gs.UpdateGrievanceDetails(GrievanceViewModel);
            if (rowAffected == 0)
            {
                ViewData["Error"] = "Data is not Updated for some reason kindly try after some time ";
                return View("Error");
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        //this is only for admin may be idk
        [HttpGet]
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Grievance/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }



        public List<CategoryViewModel> GetCategories()
        {
            List<CategoryViewModel> categories = cs.GetCategory().ToList();
            return categories;


        }


        public List<SubcategoryViewModel> GetSubcategories()
        {
            List<SubcategoryViewModel> subcategories = ss.GetSubcategory().ToList();
            return subcategories;

        }


        public JsonResult GetSubcategoriesByCategoryId(int categoryId)
        {

            List<SubcategoryViewModel> subcategories = ss.GetSubcategoryByCategoryId(categoryId).ToList();

            ViewBag.SubcatOptions = new SelectList(subcategories, "SubcategoryID", "SubcategoryName");

            //create select list item object and convert it into json Obj 
            var subcategoriesData = subcategories.Select(m => new SelectListItem()
            {
                Text = m.SubcategoryName.ToString(),
                Value = m.SubcategoryID.ToString(),
            });
            return Json(subcategoriesData, JsonRequestBehavior.AllowGet);

        }

        public ActionResult GetReplyByGrievanceId(int grievanceId)
        {
            ReplyViewModel reply = rs.GetReplyByGrievanceId(grievanceId);
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddReply(FormCollection newReply)
        {

            NewReplyViewModel reply = new NewReplyViewModel()
            {

                ReplyMessage = Request.Form["reply.ReplyMessage"],
                User_ID = Convert.ToInt32(Session["CurrentUserID"]),
                Grievance_ID = Convert.ToInt32(Request.Form["GrievanceID"]),

            };
            int rowAffected = rs.InsertReply(reply);
            return RedirectToAction("Details", new { id = reply.Grievance_ID });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditReply(FormCollection newReply)
        {

            EditReplyViewModel reply = new EditReplyViewModel()
            {

                ReplyMessage = Request.Form["reply.ReplyMessage"],
                User_ID = Convert.ToInt32(Session["CurrentUserID"]),
                Grievance_ID = Convert.ToInt32(Request.Form["reply.Grievance_ID"]),
                ReplyID = Convert.ToInt32(Request.Form["reply.ReplyID"]),
            };

GrievanceSystem_Mvc/Views/Grievance/AllGrievances.cshtml
@model IEnumerable<GrievanceSystem_Mvc.ViewModels.GrievanceViewModel>

@{
	ViewBag.Title = "All Grievances";
	Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="container card my-4 grievancecontainer ">
	<div class="row p-3">
		<div class="col-md-12">
			<span class="h5 pt-1"><strong>All Grievances</strong></span>
		</div>
	</div>
	<hr class="m-0" />
	<div class="row  p-4">
		<div class="col-md-12">
			<table class="table table-responsive table-sm table-striped table-bordered" id="grievanceTable" style="width:100%">
				<thead>
					<tr>
						<th>
							Subject
						</th>
						<th>
							Description
						</th>
						<th>
							Reported Date
						</th>
						<th>
							Status
						</th>
						<th class="m-2">Actions</th>
					</tr>
				</thead>
			</table>
		</div>
	</div>
</div>

GrievanceSystem_Mvc/Views/Grievance/Create.cshtml
@model GrievanceSystem_Mvc.ViewModels.NewGrievanceViewModel

@{
	ViewBag.Title = "Create";
	Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@* TODO:while creating grievance we have to send user id also*@

<div class="container card my-4">
	<div class="row p-3">
		<div class="col-md-12">
			<span class="h5 pt-1"><strong>Create a Grievances</strong></span>
		</div>
	</div>
	<hr class="m-0" />
	<div class="row  p-4 justify-content-center">
		<div class="col-md-12">
			@using (Html.BeginForm("Create", "Grievance", FormMethod.Post, new { @enctype = "multipart/form-data" }))
			{
				@Html.AntiForgeryToken()
				<div class="form-horizontal">
					@Html.ValidationSummary(true, "", new { @class = "text-danger" })

					<div class="form-group">
						@Html.LabelFor(model => model.subject, htmlAttributes: new { @class = "control-label col-md" })
						<div class="col">
							@Html.TextBoxFor(model => model.subject, new { @class = "form-control" })
							@Html.ValidationMessageFor(model => model.subject, "", new { @class = "text-danger" })
						</div>
					</div>

					<div class="form-group">
						@Html.LabelFor(model => model.category, htmlAttributes: new { @class = "control-label col-md" })
						<div class="col">
							@Html.DropDownListFor(model => model.category_id, new SelectList(ViewBag.categories as System.Collections.IEnumerable, "CategoryID", "CategoryName"), "Select Category", new { id = "dd_Category", @class = "form-control input-width" })
							@Html.ValidationMessageFor(model => model.category_id, "", new { @class = "text-danger" })
						</div>
					</div>

					<div class="form-group">
						@Html.LabelFor(model => model.subcategory, htmlAttributes: new { @class = "control-label col-md" })
						<div class="col">
							@Html.DropDownListFor(Model => Model.subcategory_id, new SelectList(Enumerable.Empty<SelectListItem>(), "SubcategoryID", "SubcategoryName"),
						   "Select Subcategory", new { id = "dd_Subcat", @class = "form-control input-width" })

							@Html.ValidationMessageFor(model => model.subcategory_id, "", new { @class = "text-danger" })
						</div>
					</div>

					<div class="form-group">
						@Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md" })
						<div class="col">
							@Html.TextAreaFor(model => model.description, 3, 20, new { @class = "form-control" })
							@Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
						</div>
					</div>

					<div class="form-group">
						<label for="Image" class="control-label col-md-10">Upload Picture/Screenshot (If any)</label>
						<div class="col">
							<div class="custom-file">
								<input class="custom-file-input" id="file" name="file" type="file" value="">
								<label class="custom-file-label" for="file">Choose file</label>
								<small class="text-danger">(Only .jpeg, .jpg, .pdf files allowed And File size between 15 KB To 256 KB)</small>
							</div>
						</div>
					</div>



					<p class="col-md  text-center mt-4">
						<input type="submit" value="Submit Grievance" class="btn btn-grievance shadow-none" />
					</p>

				</div>
			}

		</div>
	</div>
</div>

GrievanceSystem_Mvc/Views/Grievance/Details.cshtml
@model GrievanceSystem_Mvc.ViewModels.GrievanceViewModel
@*@using System.Web.Mvc.AssetVersioning;*@

@{
	ViewBag.Title = "Details";
	Layout = "~/Views/Shared/_AdminLayout.cshtml";
	var imgPath = "~/File/" + (Model.file ?? "");
}

<div class="container card my-4  ">
	<div class="row p-3">
		<div class="col-md-12">
			<span class="h5 pt-1"><strong>Grievance Details</strong></span>
		</div>
	</div>
	<hr class="m-0" />
	<div class="row  p-4">
		<div class=" col-md-8 card p-3 ">
			<div class="card-title">
				<b class="">Details</b>
			</div>
			<table class="table replycontainer">
				<tr class="p-1">
					<td><span class="h6">@Html.DisplayNameFor(model => model.Subject) </span></td>
					<td class=""> @Html.DisplayFor(model => model.Subject) </td>
				</tr>
				<tr>
					<td><span class="h6">@Html.DisplayNameFor(model => model.Description) </span></td>
					<td>@Html.DisplayFor(model => model.Description) </td>
				</tr>
				<tr>
					<td><span class="h6">@Html.DisplayNameFor(model => model.file) </span></td>
					@if (String.IsNullOrEmpty(Model.file))
					{
						<td>
							<span>NA</span>
						</td>
					}
					else
					{
						<td>
							<a href="@Url.Content(imgPath)" class=" btn btn-outline-dark details FilePopup" title="File Details">View File</a>
						</td>
					}
				</tr>
				<tr>

					@if (User.IsInRole("Committee Member"))
					{
						<td><span class="h6">@Html.DisplayNameFor(model => model.reply.ReplyMessage) </span></td>

						if (String.IsNullOrEmpty(Model.reply.ReplyMessage))
						{
							<td class="">
								@using (Html.BeginForm("AddReply", "Grievance", FormMethod.Post, new { id = "RegistrationForm" }))
								{
									@Html.AntiForgeryToken()
									<div class="form-horizontal">

										@Html.ValidationSummary(true, "", new { @class = "text-danger" })
										@Html.HiddenFor(model => model.GrievanceID, new { @class = "form-control" })


										<div class="form-group">
											<div class="col-md">
												@Html.TextAreaFor(model => model.reply.ReplyMessage, new { @class = "form-control" })
												@Html.ValidationMessageFor(model => model.reply.ReplyMessage, "", new { @class = "text-danger" })
											</div>
										</div>

										<div class="form-group">
											<p class="col-md mr-1">
												<input type="submit" value="Reply" class="btn btn-info mx-2 shadow-none  ">
											</p>
										</div>
									</div>
								}
							</td>


						}
						else
						{
							<td class="">
								<p class="Reply">@Html.DisplayFor(model => model.reply.ReplyMessage) </p>
								<a href="#" class="btn btn-info mr-1 mt-2 shadow-none replypopup">Edit</a>


								@using (Html.BeginForm("EditReply", "Grievance", FormMethod.Post, new { id = "EditReply", @class = "replyform hidden" }))
								{
									@Html.AntiForgeryToken()
									<div class="form-horizontal">

										@Html.ValidationSummary(true, "", new { @class = "text-danger" })
										@Html.HiddenFor(model => model.GrievanceID, new { @class = "form-control" })
										@Html.HiddenFor(model => model.reply.ReplyID, new { @class = "form-control" })
										@Html.HiddenFor(model => model.reply.Grievance_ID, new { @class = "form-control" })

										<div class="form-group">
											<div class="col-md">
												@Html.TextAreaFor(model => model.reply.ReplyMessage, new { @class = "form-control" })
												@Html.ValidationMessageFor(model => model.reply.ReplyMessage, "", new { @class = "text-danger" })
											</div>
										</div>

										<div class="form-group">
											<p class="col-md mr-1">
												<input type="submit" value="Update Reply" class="btn btn-info shadow-none">
											</p>
										</div>
									</div>
								}

							</td>

						}
					}
					else if (String.IsNullOrEmpty(Model.reply.ReplyMessage) && User.IsInRole("Student"))
					{
						<td>
							<span class="h6">@Html.DisplayNameFor(model => model.reply.ReplyMessage) </span>
						</td>
						<td class="">
							NA
						</td>
					}


				</tr>

			</table>

		</div>
		<div id="dialogNew" class="" style="display:none" title=""></div>
		<div class="col-md-4 mt-sm-2 mt-md-0">
			<div class="card p-3">
				<div class="card-title">
					<b class="">Details</b>

				</div>
				<table class="table table-responsive">
					<tbody>
						@*<tr class="">
								<td class="h6">@Html.DisplayNameFor(model => model.GrievanceID)</td>
								<td> @Html.DisplayFor(model => model.GrievanceID)</td>
							</tr>*@
						<tr>
							<td class="h6">@Html.DisplayNameFor(model => model.ReportedDate)</td>
							<td> @Html.DisplayFor(model => model.ReportedDate)</td>
						</tr>

						<tr>
							<td class="h6">@Html.DisplayNameFor(model => model.category.CategoryName)</td>
							<td> @Html.DisplayFor(model => model.category.CategoryName) </td>
						</tr>

						<tr>
							<td class="h6">@Html.DisplayNameFor(model => model.subcategory.SubcategoryName)</td>
							<td> @Html.DisplayFor(model => model.subcategory.SubcategoryName)</td>
						</tr>
						<tr>
							<td class="h6">@Html.DisplayNameFor(model => model.Status)</td>
							<td>  @Html.DisplayFor(model => model.Status)</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>

	</div>
	<div class="row p-3">
		@* edit button is only available for Students Admin cannot edit grievance but admin can view and reply grievance *@

		@if (User.IsInRole("Student"))
		{
			<a href="@Url.Action("Edit","Grievance",new { id= Model.GrievanceID}) " class="btn btn-outline-primary	 ml-3">Update Grievance</a>
			if (!String.IsNullOrEmpty(Model.reply.ReplyMessage))
			{

				<!-- Button trigger modal -->
				<button type="button" class="btn btn-outline-success ml-3" data-toggle="modal" data-target="#replyModalCenter">
					Reply Details
				</button>

				<!-- Modal -->
				<div class="modal fade" id="replyModalCenter" tabindex="-1" role="dialog" aria-labelledby="replyModalCenterTitle" aria-hidden="true">
					<div class="modal-dialog modal-dialog-centered" role="document">
						<div class="modal-content">
							<div class="modal-header">
								<h5 class="modal-title" id="exampleModalLongTitle">Reply Details</h5>
								<button type="button" class="close" data-dismiss="modal" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
							</div>
							<div class="modal-body">

								<table class="table table-responsive ">
									<tbody>

										<tr>
											<td class="border-0"><span class="h6">@Html.DisplayNameFor(m => m.reply.ReplyMessage)</span></td>
											<td class="border-0">@Html.DisplayFor(m => m.reply.ReplyMessage)</td>
										</tr>
										<tr>
											<td><span class="h6">@Html.DisplayNameFor(model => model.reply.ReplyDate) </span></td>
											<td>@Html.DisplayFor(model => model.reply.ReplyDate) </td>
										</tr>
									</tbody>
								</table>



							</div>
						</div>
					</div>
				</div>
			}


		}

	</div>

</div>

GrievanceSystem_Mvc/Views/Grievance/Edit.cshtml
@model GrievanceSystem_Mvc.ViewModels.GrievanceViewModel

@{
	ViewBag.Title = "Edit";
	Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="container card my-4">
	<div class="row p-3">
		<div class="col-md-12">
			<span class="h5 pt-1"><strong>Update Grievances</strong></span>
		</div>
	</div>
	<hr class="m-0" />
	<div class="row  p-4 justify-content-center">
		<div class="col-md-12">
			@using (Html.BeginForm("Edit", "Grievance", FormMethod.Post))
			{
				@Html.AntiForgeryToken()
				@Html.HiddenFor(model => model.GrievanceID)

				<div class="form-horizontal">
					@Html.ValidationSummary(true, "", new { @class = "text-danger" })
					<div class="form-group">
						@Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md" })
						<div class="col">
							@Html.TextBoxFor(model => model.Subject, new { @class = "form-control" })
							@Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
						</div>
					</div>


					<div class="form-group">
						@Html.LabelFor(model => model.category.CategoryName, htmlAttributes: new { @class = "control-label col-md" })
						<div class="col">
							@Html.DropDownListFor(model => model.category.CategoryID, new SelectList(ViewBag.categories as System.Collections.IEnumerable, "CategoryID", "CategoryName"), "--Select Category--", new { id = "dd_Category", @class = "form-control input-width" })
							@Html.ValidationMessageFor(model => model.category.CategoryID, "", new { @class = "text-danger" })
						</div>
					</div>

					<div class="form-group">
						@Html.LabelFor(model => model.subcategory.SubcategoryName, htmlAttributes: new { @class = "control-label col-md" })
						<div class="col">
							@Html.DropDownListFor(Model => Model.subcategory.SubcategoryID, new SelectList(ViewBag.subcategories as System.Collections.IEnumerable, "SubcategoryID", "SubcategoryName"),
						   "--Select Subcategory--", new { id = "dd_Subcat", @class = "form-control input-width" })

							@Html.ValidationMessageFor(model => model.subcategory.SubcategoryID, "", new { @class = "text-danger" })
						</div>
					</div>

					<div class="form-group">
						@Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md" })
						<div class="col">
							@Html.TextAreaFor(model => model.Description, 6, 20, new { @class = "form-control" })
							@Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
						</div>
					</div>
					<p class="col-md  text-center mt-4">
						<input type="submit" value="Update" class="btn btn-grievance shadow-none" />
					</p>

				</div>
			}
		</div>
	</div>
</div>

GrievanceSystem_Mvc/Views/Grievance/Index.cshtml
@model IEnumerable<GrievanceSystem_Mvc.ViewModels.GrievanceViewModel>

@{
	ViewBag.Title = "Index";
	Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container card my-4">
	<div class="row p-3">
		<div class="col-md-12">
			<span class="h5 pt-1"><strong>All Grievances</strong></span>
			<a href="@Url.Action("Create","Grievance") " class="btn btn-outline-dark rounded-pill float-right">
				<span class="px-3 font-weight-bold">
					+ Add Grievnace
				</span>
			</a>
		</div>
	</div>
	<hr class="m-0" />
	<div class="row  p-4 justify-content-center">
		<div class="col-md-12">
			<table class="table table-responsive table-hover border-0 table-bordered">
				<caption>List of Grievances </caption>
				<thead class="thead-light">
					<tr>
						@*<th>
								@Html.DisplayNameFor(model => model.GrievanceID)
							</th>*@

						<th style="min-width:200px;">
							@Html.DisplayNameFor(model => model.Subject)
						</th>
						<th style="min-width:500px;">
							@Html.DisplayNameFor(model => model.Description)
						</th>
						<th style=" width:110px;">
							@Html.DisplayNameFor(model => model.ReportedDate)
						</th>
						<th style=" width:auto;" >
							@Html.DisplayNameFor(model => model.Status)
						</th>
						<th class="" colspan="1" rowspan="1" style="width:169px;">Actions</th>
					</tr>

				</thead>
				<tbody>
					@foreach (var item in Model)
					{
						<tr>
							@*<td>
									@Html.DisplayFor(modelItem => item.GrievanceID)
								</td>*@
							<td>
								@Html.DisplayFor(modelItem => item.Subject)
							</td>
							<td>
								@Html.DisplayFor(modelItem => item.Description)
							</td>
							<td>
								@Html.DisplayFor(modelItem => item.ReportedDate)
							</td>
							<td>
								@if (item.Status == "Open")
								{
									<span class="badge badge-warning">
										@Html.DisplayFor(modelItem => item.Status)
									</span>
								}
								else
								{
									<span class="badge badge-info">
										@Html.DisplayFor(modelItem => item.Status)

									</span>

								}

							</td>
							<td style="width:175px">

								@Html.ActionLink("View", "Details", "Grievance", new { id = item.GrievanceID }, new { @class = "btn btn-outline-info my-1" })
								@Html.ActionLink("Update", "Edit", "Grievance", new { id = item.GrievanceID }, new { @class = "btn btn-outline-danger my-1" })
								@*@Html.ActionLink("View Reply", "Reply", "Grievance", new { id = item.GrievanceID }, new { @class = "btn btn-outline-danger" })*@
							</td>

						</tr>
					}
				</tbody>
			</table>


		</div>
	</div>
</div>

GrievanceSystem_Mvc/Views/Grievance/PendingGrievances.cshtml
@model IEnumerable<GrievanceSystem_Mvc.ViewModels.GrievanceViewModel>

@{
	ViewBag.Title = "Pending Grievances";
	Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="container card my-4 grievancecontainer ">
	<div class="row p-3">
		<div class="col-md-12">
			<span class="h5 pt-1"><strong>Pending Grievances</strong></span>
		</div>
	</div>
	<hr class="m-0" />
	<div class="row  p-4">
		<div class="col-md-12">
			<table class="table table-responsive table-sm table-striped table-bordered" id="PendinggrievanceTable" style="width:100%">
				<thead>
					<tr>
						<th>S.No</th>
						<th>
							Subject
						</th>
						<th>
							Description
						</th>
						<th>
							Reported Date
						</th>
						<th>
							Status
						</th>
						<th class="m-2">Actions</th>
					</tr>
				</thead>
			</table>
		</div>
	</div>
</div>